name: Lint .proto files

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  lint:
    name: lint .proto files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install buf
        run: |
         BIN="/usr/local/bin" && \
         VERSION="1.0.0-rc12" && \
         curl -sSL \
         "https://github.com/bufbuild/buf/releases/download/v${VERSION}/buf-$(uname -s)-$(uname -m)" \
         -o "${BIN}/buf" && \
         chmod +x "${BIN}/buf"
         cat <<EOF > buf.yaml
         version: v1
         lint:
           use:
             - DEFAULT
           except:
             - RPC_REQUEST_STANDARD_NAME
             - RPC_RESPONSE_STANDARD_NAME
         EOF
      - name: Run linter
        run: buf lint proto --config ./buf.yaml
