name: Lint .proto files

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  lint:
    name: buf check lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ory/build-buf-action@v0
        with:
          bufVersion: v0.31.1
          bufArgs: check lint --path mt